### ISSUE TITLE
_PyV8.so: undefined symbol: u_strToLower_58

### ISSUE THREAD

**Issue by sundod** [jmalonzo/pyv8#7]
[root@websec3 opt]# thug
Traceback (most recent call last):
  File "/usr/bin/thug", line 11, in <module>
    load_entry_point('thug==0.8.15', 'console_scripts', 'thug')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 561, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2627, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2287, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2293, in resolve
  File "build/bdist.linux-x86_64/egg/thug/thug.py", line 24, in <module>
  File "build/bdist.linux-x86_64/egg/thug/ThugAPI/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/thug/ThugAPI/ThugAPI.py", line 22, in <module>
  File "build/bdist.linux-x86_64/egg/PyV8.py", line 33, in <module>
  File "build/bdist.linux-x86_64/egg/_PyV8.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/_PyV8.py", line 6, in __bootstrap__
ImportError: /root/.cache/Python-Eggs/PyV8-1.0.dev0-py2.7-linux-x86_64.egg-tmp/_PyV8.so: undefined symbol: u_strToLower_58

**Comment by jmalonzo** [comment]
@sundod Please build v8 without i18nsupport or use the previous working commit. I don't think the latest HEAD works out of the box.
